<?php
namespace SEOstats\Services;
use SEOstats\SEOstats as SEOstats;
use SEOstats\Config as Config;
use SEOstats\Helper as Helper;
class Social extends SEOstats{
  public static function getGoogleShares($url=false){return self::getGooglePlusShares($url);}
  public static function getGooglePlusShares($url=false){$url=parent::getUrl($url);$dataUrl=sprintf(Config\Services::GOOGLE_PLUSONE_URL,urlencode($url));$html=parent::_getPage($dataUrl);@preg_match_all('/window\.__SSR\s\=\s\{c:\s(\d+?)\./',$html,$match,PREG_SET_ORDER);return(1===sizeof($match)&&2===sizeof($match[0]))?intval($match[0][1]):parent::noDataDefaultValue();}
  public static function getFacebookShares($url=false){$url=parent::getUrl($url);$fql=sprintf('SELECT total_count,share_count,like_count,comment_count,commentsbox_count,click_count FROM link_stat WHERE url="%s"',$url);$dataUrl=sprintf(Config\Services::FB_LINKSTATS_URL,rawurlencode($fql));$jsonData=parent::_getPage($dataUrl);$phpArray=Helper\Json::decode($jsonData,true);return isset($phpArray[0])?$phpArray[0]:parent::noDataDefaultValue();}
  public static function getTwitterShares($url=false){$url=parent::getUrl($url);$dataUrl=sprintf(Config\Services::TWEETCOUNT_URL,urlencode($url));$jsonData=parent::_getPage($dataUrl);$phpArray=Helper\Json::decode($jsonData,true);return isset($phpArray['count'])?intval($phpArray['count']):parent::noDataDefaultValue();}
  public static function getDeliciousShares($url=false){$url=parent::getUrl($url);$dataUrl=sprintf(Config\Services::DELICIOUS_INFO_URL,urlencode($url));$jsonData=parent::_getPage($dataUrl);$phpArray=Helper\Json::decode($jsonData,true);return isset($phpArray[0]['total_posts'])?intval($phpArray[0]['total_posts']):parent::noDataDefaultValue();}
  public static function getDeliciousTopTags($url=false){$url=parent::getUrl($url);$dataUrl=sprintf(Config\Services::DELICIOUS_INFO_URL,urlencode($url));$jsonData=parent::_getPage($dataUrl);$phpArray=Helper\Json::decode($jsonData,true);$ret=array();if(isset($phpArray[0]['top_tags'])&&0<sizeof($phpArray[0]['top_tags'])){foreach($phpArray[0]['top_tags']as$k=>$v){$ret[]=$k;}}return$ret;}
  public static function getDiggShares($url=false){$url=parent::getUrl($url);$dataUrl=sprintf(Config\Services::DIGG_INFO_URL,urlencode($url));$jsonData=parent::_getPage($dataUrl);$phpArray=Helper\Json::decode(substr($jsonData,2,-2),true);return isset($phpArray['diggs'])?intval($phpArray['diggs']):parent::noDataDefaultValue();}
  public static function getLinkedInShares($url=false){$url=parent::getUrl($url);$dataUrl=sprintf(Config\Services::LINKEDIN_INFO_URL,urlencode($url));$jsonData=parent::_getPage($dataUrl);$phpArray=Helper\Json::decode(substr($jsonData,2,-2),true);return isset($phpArray['count'])?intval($phpArray['count']):parent::noDataDefaultValue();}
  public static function getPinterestShares($url=false){$url=parent::getUrl($url);$dataUrl=sprintf(Config\Services::PINTEREST_INFO_URL,urlencode($url));$jsonData=parent::_getPage($dataUrl);$phpArray=Helper\Json::decode(substr($jsonData,2,-1),true);return isset($phpArray['count'])?intval($phpArray['count']):parent::noDataDefaultValue();}
  public static function getStumbleUponShares($url=false){$url=parent::getUrl($url);$dataUrl=sprintf(Config\Services::STUMBLEUPON_INFO_URL,urlencode($url));$jsonData=parent::_getPage($dataUrl);$phpArray=Helper\Json::decode($jsonData,true);return isset($phpArray['result']['in_index'])&&true==$phpArray['result']['in_index']?intval($phpArray['result']['views']):parent::noDataDefaultValue();}
  public static function getVKontakteShares($url=false){$url=parent::getUrl($url);$dataUrl=sprintf(Config\Services::VKONTAKTE_INFO_URL,urlencode($url));$htmlData=parent::_getPage($dataUrl);@preg_match_all('#^VK\.Share\.count\(1, (\d+)\);$#si',$htmlData,$matches);return isset($matches[1][0])?intval($matches[1][0]):parent::noDataDefaultValue();}
  public static function getXingShares($url=false){$host=parent::getHost($url);$dataUrl=sprintf(Config\Services::XING_SHAREBUTTON_URL,urlencode($host));$htmlData=parent::_getPage($dataUrl);@preg_match_all('/\r?\n(\d+)\r?\n/s',$htmlData,$matches);if(isset($matches[1])&&4==sizeof($matches[1]))return array('shares'=>intval($matches[1][0]),'comments'=>intval($matches[1][1]),'clicks'=>intval($matches[1][2]),'reach'=>intval($matches[1][3]));return parent::noDataDefaultValue();}
}
