<?php
session_start();
$tx="abcdefghijklmnopqrstuvwxyz";
$i=strlen($tx);
$t="";
$l=rand(4,8);
while($l>0){
	$z=rand(0,$i);
	$ul=rand(0,100);
	$t.=strtolower($tx{$z});
	$l--;
}
$_SESSION['v']=strtolower($t);
$x=210;
$y=40;
$img=imagecreatetruecolor($x,$y);
$col1=imagecolorallocate($img,rand(0,64),rand(0,64),rand(0,64));
$col2=imagecolorallocate($img,rand(64,128),rand(64,128),rand(64,128));
$col3=imagecolorallocate($img,rand(128,192),rand(128,255),rand(128,192));
$col4=imagecolorallocate($img,rand(192,255),rand(192,255),rand(192,255));
$white=imagecolorallocate($img,255,255,255);imagefill($img,0,0,$col1);
for($i=0;$i<$x;$i++){
	for($j=0;$j<$y;$j++){
		if(mt_rand(0,10)<2)imagesetpixel($img,$i,$j,$col2);
		if(mt_rand(0,10)<5)imagesetpixel($img,$i,$j,$col3);
		if(mt_rand(0,10)<5)imagesetpixel($img,$i,$j,$col4);
	}
}
imagefilter($img,IMG_FILTER_GAUSSIAN_BLUR,5);
imagefilter($img,IMG_FILTER_SMOOTH,5);
for($i=0;$i<$x;$i++){
	for($j=0;$j<$y;$j++){
		if(mt_rand(0,10)<2)imagesetpixel($img,$i,$j,$white);
		if(mt_rand(0,10)<5)imagesetpixel($img,$i,$j,$white);
	}
}
imagefilter($img,IMG_FILTER_GAUSSIAN_BLUR,5);
imagefilter($img,IMG_FILTER_SMOOTH,5);
$x=rand(5,25);
$y=rand(2,10);
$tC=imagecolorallocate($img,0,0,0);
$f=imageloadfont('arial.gdf');
imagestring($img,$f,$x+1,$y+1,$t,$tC);
imagestring($img,$f,$x-1,$y-1,$t,$tC);
imagestring($img,$f,$x+1,$y-1,$t,$tC);
imagestring($img,$f,$x-1,$y+1,$t,$tC);
imagestring($img,$f,$x+2,$y+2,$t,$tC);
imagestring($img,$f,$x-2,$y-2,$t,$tC);
imagestring($img,$f,$x+2,$y-2,$t,$tC);
imagestring($img,$f,$x-2,$y+2,$t,$tC);
$tC=imagecolorallocate($img,rand(192,255),rand(192,255),rand(192,255));
imagestring($img,$f,$x,$y,$t,$tC);
header('Content-type:image/jpeg');
imagejpeg($img);
imagedestroy($img);
