<?php
$content.='<main id="content" class="col-md-12">';
	$content.='<div class="panel panel-default">';
		$content.='<div class="panel-body">';
if($user['rank']>699){
	if($args[0]=='add'){
		$type=filter_input(INPUT_GET,'type',FILTER_SANITIZE_STRING);
		$q=$db->prepare("INSERT INTO login (rank,active,ti) VALUES ('0','1',:ti)");
		$q->execute(array(':ti'=>$ti));
		$args[1]=$db->lastInsertId();
		$show="User ".$args[1];
		$q=$db->prepare("UPDATE login SET username=:username WHERE id=:id");
		$q->execute(array(':username'=>$show,':id'=>$args[1]));
		$args[0]='edit';
	}
	if($args[0]=='edit'){
		$q=$db->prepare("SELECT * FROM login WHERE id=:id");
		$q->execute(array(':id'=>$args[1]));
		$r=$q->fetch(PDO::FETCH_ASSOC);
			$content.='<div class="form-group">';
				$content.='<label for="ti" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">Created</label>';
				$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
					$content.='<input type="text" id="ti" class="form-control textinput" value="'.date($config['dateFormat'],$r['ti']).'" readonly>';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="form-group">';
				$content.='<label for="username" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">Username</label>';
				$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
					$content.='<input type="text" id="username" class="form-control textinput" value="'.$r['username'].'" data-dbid="'.$r['id'].'" data-dbt="login" data-dbc="username" placeholder="Enter a Username...">';
					$content.='<div id="usernamesave" class="input-group-btn hidden">';
						$content.='<button class="btn btn-danger">Save</button>';
					$content.='</div>';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="form-group">';
				$content.='<label for="password" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">Password</label>';
				$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
					$content.='<input type="password" id="password" class="form-control textinput" value="'.$r['password'].'" data-dbid="'.$r['id'].'" data-dbt="login" data-dbc="password" placeholder="Enter a Password...">';
					$content.='<div id="passwordsave" class="input-group-btn hidden">';
						$content.='<button class="btn btn-danger">Save</button>';
					$content.='</div>';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="form-group">';
				$content.='<label for="rank" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">Rank</label>';
				$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
		if($r['rank']<1000){
					$content.='<select id="rank" class="form-control" onchange="update(\''.$r['id'].'\',\'login\',\'rank\',$(this).val());">';
						$content.='<option value="0"';if($r['rank']==0){$content.=' selected';}$content.='>Visitor</option>';
						$content.='<option value="100"';if($r['rank']==100){$content.=' selected';}$content.='>Subscriber</option>';
						$content.='<option value="200"';if($r['rank']==200){$content.=' selected';}$content.='>Member</option>';
						$content.='<option value="300"';if($r['rank']==300){$content.=' selected';}$content.='>Client</option>';
						$content.='<option value="400"';if($r['rank']==400){$content.=' selected';}$content.='>Contributor</option>';
						$content.='<option value="500"';if($r['rank']==500){$content.=' selected';}$content.='>Moderator</option>';
						$content.='<option value="600"';if($r['rank']==600){$content.=' selected';}$content.='>Author</option>';
						$content.='<option value="700"';if($r['rank']==700){$content.=' selected';}$content.='>Editor</option>';
						$content.='<option value="800"';if($r['rank']==800){$content.=' selected';}$content.='>Manager</option>';
						$content.='<option value="900"';if($r['rank']==900){$content.=' selected';}$content.='>Administrator</option>';
			if($user['rank']==1000){
						$content.='<option value="1000"';if($r['rank']==1000){$content.=' selected';}$content.='>Developer</option>';
			}
					$content.='</select>';
		}else{
			$content.='Developer';
		}
				$content.='</div>';
			$content.='</div>';
		if($r['rank']<1000){
			$content.='<div class="well">';
				$content.='<h4>Editing Permissions</h4>';
				$content.='<div class="form-group">';
					$content.='<label for="options0" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4 text-right">';
						$content.='<input type="checkbox" id="options0" data-dbid="'.$r['id'].'" data-dbt="login" data-dbc="options" data-dbb="0"';if($r['options']{0}==1){$content.=' checked';}$content.='>';
					$content.='</label>';
					$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
						$content.='<strong>Add Content</strong>';
					$content.='</div>';
				$content.='</div>';
				$content.='<div class="form-group">';
					$content.='<label for="options1" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4 text-right">';
						$content.='<input type="checkbox" id="options1" data-dbid="'.$r['id'].'" data-dbt="login" data-dbc="options" data-dbb="1"';if($r['options']{1}==1){$content.=' checked';}$content.='>';
					$content.='</label>';
					$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
						$content.='<strong>SEO Viewing/Editing</strong>';
					$content.='</div>';
				$content.='</div>';
				$content.='<div class="form-group">';
					$content.='<label for="options2" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4 text-right">';
						$content.='<input type="checkbox" id="options2" data-dbid="'.$r['id'].'" data-dbt="login" data-dbc="options" data-dbb="2"';if($r['options']{2}==1){$content.=' checked';}$content.='>';
					$content.='</label>';
					$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
						$content.='<strong>Message Viewing/Editing</strong>';
					$content.='</div>';
				$content.='</div>';
				$content.='<div class="form-group">';
					$content.='<label for="options3" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4 text-right">';
						$content.='<input type="checkbox" id="options3" data-dbid="'.$r['id'].'" data-dbt="login" data-dbc="options" data-dbb="3"';if($r['options']{3}==1){$content.=' checked';}$content.='>';
					$content.='</label>';
					$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
						$content.='<strong>Orders Viewing/Editing</strong>';
					$content.='</div>';
				$content.='</div>';
				$content.='<div class="form-group">';
					$content.='<label for="options4" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4 text-right">';
						$content.='<input type="checkbox" id="options4" data-dbid="'.$r['id'].'" data-dbt="login" data-dbc="options" data-dbb="4"';if($r['options']{4}==1){$content.=' checked';}$content.='>';
					$content.='</label>';
					$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
						$content.='<strong>Administration Viewing/Editing</strong>';
					$content.='</div>';
				$content.='</div>';
				$content.='<div class="form-group">';
					$content.='<label for="options5" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4 text-right">';
						$content.='<input type="checkbox" id="options5" data-dbid="'.$r['id'].'" data-dbt="login" data-dbc="options" data-dbb="5"';if($r['options']{5}==1){$content.=' checked';}$content.='>';
					$content.='</label>';
					$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
						$content.='<strong>User Accounts Viewing/Editing</strong>';
					$content.='</div>';
				$content.='</div>';
			$content.='</div>';
		}
			$content.='<div class="well">';
				$content.='<form target="sp" method="post" enctype="multipart/form-data" action="includes/add_data.php">';
					$content.='<input type="hidden" name="id" value="'.$r['id'].'">';
					$content.='<input type="hidden" name="act" value="add_avatar">';
					$content.='<div class="form-group">';
						$content.='<label for="avatar" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">Avatar</label>';
						$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
							$content.='<input type="file" name="fu" class="form-control" data-icon="false">';
							$content.='<div class="input-group-btn">';
								$content.='<button class="btn btn-default" type="submit">Upload</button>';
							$content.='</div>';
						$content.='</div>';
					$content.='</div>';
				$content.='</form>';
				$content.='<div class="form-group">';
					$content.='<label for="gravatar" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">Gravatar</label>';
					$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
						$content.='<input type="text" id="gravatar" class="form-control textinput" value="'.$r['gravatar'].'" data-dbid="'.$r['id'].'" data-dbt="login" data-dbc="gravatar" placeholder="Enter Gravatar Link...">';
						$content.='<div id="gravatarsave" class="input-group-btn hidden">';
							$content.='<button class="btn btn-danger">Save</button>';
						$content.='</div>';
					$content.='</div>';
				$content.='</div>';
				$content.='<div class="form-group">';
					$content.='<label class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">&nbsp;</label>';
					$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
						$content.='<div class="alert alert-info"><a target="_blank" href="http://www.gravatar.com/">Gravatar</a> Link will override any image uploaded as your Avatar.</div>';
					$content.='</div>';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="form-group">';
				$content.='<label for="email" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">Email</label>';
				$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
					$content.='<input type="text" id="email" class="form-control textinput" value="'.$r['email'].'" data-dbid="'.$r['id'].'" data-dbt="login" data-dbc="email" placeholder="Enter an Email...">';
					$content.='<div id="emailsave" class="input-group-btn hidden">';
						$content.='<button class="btn btn-danger">Save</button>';
					$content.='</div>';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="form-group">';
				$content.='<label for="name" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">Name</label>';
				$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
					$content.='<input type="text" id="name" class="form-control textinput" value="'.$r['name'].'" data-dbid="'.$r['id'].'" data-dbt="login" data-dbc="name" placeholder="Enter a Name...">';
					$content.='<div id="namesave" class="input-group-btn hidden">';
						$content.='<button class="btn btn-danger">Save</button>';
					$content.='</div>';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="form-group">';
				$content.='<label for="url" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">URL</label>';
				$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
					$content.='<input type="text" id="url" class="form-control textinput" value="'.$r['url'].'" data-dbid="'.$r['id'].'" data-dbt="login" data-dbc="url" placeholder="Enter a URL...">';
					$content.='<div id="urlsave" class="input-group-btn hidden">';
						$content.='<button class="btn btn-danger">Save</button>';
					$content.='</div>';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="form-group">';
				$content.='<label for="business" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">Business</label>';
				$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
					$content.='<input type="text" id="business" class="form-control textinput" value="'.$r['business'].'" data-dbid="'.$r['id'].'" data-dbt="login" data-dbc="business" placeholder="Enter a Business...">';
					$content.='<div id="businesssave" class="input-group-btn hidden">';
						$content.='<button class="btn btn-danger">Save</button>';
					$content.='</div>';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="form-group">';
				$content.='<label for="phone" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">Phone</label>';
				$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
					$content.='<input type="text" id="phone" class="form-control textinput" value="'.$r['phone'].'" data-dbid="'.$r['id'].'" data-dbt="login" data-dbc="phone" placeholder="Enter a Phone Number...">';
					$content.='<div id="phonesave" class="input-group-btn hidden">';
						$content.='<button class="btn btn-danger">Save</button>';
					$content.='</div>';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="form-group">';
				$content.='<label for="mobile" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">Mobile</label>';
				$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
					$content.='<input type="text" id="mobile" class="form-control textinput" value="'.$r['mobile'].'" data-dbid="'.$r['id'].'" data-dbt="login" data-dbc="mobile" placeholder="Enter a Mobile Number...">';
					$content.='<div id="mobilesave" class="input-group-btn hidden">';
						$content.='<button class="btn btn-danger">Save</button>';
					$content.='</div>';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="form-group">';
				$content.='<label for="address" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">Address</label>';
				$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
					$content.='<input type="text" id="address" class="form-control textinput" name="address" value="'.$r['address'].'" data-dbid="'.$r['id'].'" data-dbt="login" data-dbc="address" placeholder="Enter an Address...">';
					$content.='<div id="addresssave" class="input-group-btn hidden">';
						$content.='<button class="btn btn-danger">Save</button>';
					$content.='</div>';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="form-group">';
				$content.='<label for="suburb" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">Suburb</label>';
				$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
					$content.='<input type="text" id="suburb" class="form-control textinput" name="suburb" value="'.$r['suburb'].'" data-dbid="'.$r['id'].'" data-dbt="login" data-dbc="suburb" placeholder="Enter a Suburb...">';
					$content.='<div id="suburbsave" class="input-group-btn hidden">';
						$content.='<button class="btn btn-danger">Save</button>';
					$content.='</div>';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="form-group">';
				$content.='<label for="city" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">City</label>';
				$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
					$content.='<input type="text" id="city" class="form-control textinput" name="city" value="'.$r['city'].'" data-dbid="'.$r['id'].'" data-dbt="login" data-dbc="city" placeholder="Enter a City...">';
					$content.='<div id="citysave" class="input-group-btn hidden">';
						$content.='<button class="btn btn-danger">Save</button>';
					$content.='</div>';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="form-group">';
				$content.='<label for="state" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">State</label>';
				$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
					$content.='<input type="text" id="state" class="form-control textinput" name="state" value="'.$r['state'].'" data-dbid="'.$r['id'].'" data-dbt="login" data-dbc="state" placeholder="Enter a State...">';
					$content.='<div id="statesave" class="input-group-btn hidden">';
						$content.='<button class="btn btn-danger">Save</button>';
					$content.='</div>';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="form-group">';
				$content.='<label for="postcode" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">Postcode</label>';
				$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
					$content.='<input type="text" id="postcode" class="form-control textinput" name="postcode" value="';if($r['postcode']!=0){$content.=$r['postcode'];}$content.='" data-dbid="'.$r['id'].'" data-dbt="login" data-dbc="postcode" placeholder="Enter a Postcode...">';
					$content.='<div id="postcodesave" class="input-group-btn hidden">';
						$content.='<button class="btn btn-danger">Save</button>';
					$content.='</div>';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="form-group">';
				$content.='<label for="order_notes" class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">About</label>';
				$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
					$content.='<form method="post" target="sp" action="includes/update.php">';
						$content.='<input type="hidden" name="id" value="'.$r['id'].'">';
						$content.='<input type="hidden" name="t" value="login">';
						$content.='<input type="hidden" name="c" value="notes">';
						$content.='<textarea id="notes" class="form-control summernote" name="da">'.$r['notes'].'</textarea>';
					$content.='</form>';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="well">';
				$content.='<h4>Social Networking</h4>';
				$content.='<div class="form-group">';
					$content.='<label class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">&nbsp;</label>';
					$content.='<form target="sp" method="post" action="includes/add_data.php">';
						$content.='<input type="hidden" name="user" value="'.$r['id'].'">';
						$content.='<input type="hidden" name="act" value="add_social">';
						$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
							$content.='<span class="input-group-addon">Network</span>';
							$content.='<select class="form-control" name="icon">';
								$content.='<option value="">None</option>';
								$content.='<option value="500px">500px</option>';
								$content.='<option value="behance-square">Behance</option>';
								$content.='<option value="blogger">Blogger</option>';
								$content.='<option value="delicious">Delcicious</option>';
								$content.='<option value="deviantart">DeviantArt</option>';
								$content.='<option value="dribble">Dribble</option>';
								$content.='<option value="facebook-square">Facebook</option>';
								$content.='<option value="flickr">Flickr</option>';
								$content.='<option value="forrst">Forrst</option>';
								$content.='<option value="github-square">GitHub</option>';
								$content.='<option value="google-plus-square">Google+</option>';
								$content.='<option value="instagram">Instagram</option>';
								$content.='<option value="lastfm-square">LastFM</option>';
								$content.='<option value="linkedin-square">Linkedin</option>';
								$content.='<option value="livejournal">LiveJournal</option>';
								$content.='<option value="myspace">MySpace</option>';
								$content.='<option value="pied-piper">Pied Piper</option>';
								$content.='<option value="pinterest-square">Pinterest</option>';
								$content.='<option value="skype">Skype</option>';
								$content.='<option value="stack-overflow">StackOverflow</option>';
								$content.='<option value="stumbleupon-circle">StumbleUpon</option>';
								$content.='<option value="tumblr-square">Tumblr</option>';
								$content.='<option value="twitter-square">Twitter</option>';
								$content.='<option value="vimeo-square">Vimeo</option>';
								$content.='<option value="youtube-square">YouTube</option>';
							$content.='</select>';
							$content.='<div class="input-group-addon">URL</div>';
							$content.='<input type="text" class="form-control" name="url" value="" placeholder="Enter a URL...">';
							$content.='<div class="input-group-btn">';
								$content.='<button class="btn btn-success">Add</button>';
							$content.='</div>';
						$content.='</div>';
					$content.='</form>';
				$content.='</div>';
				$content.='<div id="social">';
			$ss=$db->prepare("SELECT * FROM choices WHERE uid=:uid ORDER BY icon ASC");
			$ss->execute(array(':uid'=>$r['id']));
			while($rs=$ss->fetch(PDO::FETCH_ASSOC)){
					$content.='<div id="l_'.$rs['id'].'" class="form-group">';
						$content.='<label class="control-label col-lg-1 col-md-2 col-sm-2 col-xs-4">&nbsp;</label>';
						$content.='<div class="input-group col-lg-11 col-md-10 col-sm-10 col-xs-8">';
							$content.='<div class="input-group-addon">Network</div>';
							$content.='<div class="input-group-addon"><i class="fa fa-'.$rs['icon'].'"></i></div>';
							$content.='<div class="input-group-addon">URL</div>';
							$content.='<input type="text" class="form-control" value="'.$rs['url'].'" onchange="update(\''.$rs['id'].'\',\'social\',\'url\',$(this).val());" placeholder="Enter a URL...">';
							$content.='<div class="input-group-btn">';
								$content.='<form target="sp" action="includes/purge.php">';
									$content.='<input type="hidden" name="id" value="'.$rs['id'].'">';
									$content.='<input type="hidden" name="t" value="choices">';
									$content.='<button class="btn btn-danger"><i class="fa fa-trash"></i></button>';
								$content.='</form>';
							$content.='</div>';
						$content.='</div>';
					$content.='</div>';
			}
				$content.='</div>';
			$content.='</div>';
	}else{
			$content.='<div class="table-responsive">';
				$content.='<table class="table table-condensed sort_table">';
					$content.='<thead>';
						$content.='<tr>';
							$content.='<th>Username</th>';
							$content.='<th>Name</th>';
							$content.='<th>Email</th>';
							$content.='<th class="col-sm-2">Rank</th>';
							$content.='<th class="col-sm-3">';
								$content.='<div class="input-group" data-tooltip data-original-title="Enter text to filter out unwanted Accounts">';
									$content.='<input type="text" class="form-control filter" placeholder="Enter Text to Filter...">';
									$content.='<div class="input-group-addon">Filter</div>';
								$content.='</div>';
							$content.='</th>';
							$content.='<th class="hidden"></th>';
							$content.='<th class="hidden"></th>';
						$content.='</tr>';
					$content.='</thead>';
					$content.='<tbody id="sort">';
		$s=$db->prepare("SELECT * FROM login WHERE rank<:rank ORDER BY ti ASC");
		$s->execute(array(':rank'=>$user['rank']+1));
		while($r=$s->fetch(PDO::FETCH_ASSOC)){
			if($user['rank']>900&&$r['status']=='delete') continue;
						$content.='<tr id="l_'.$r['id'].'" data-id="'.$r['id'].'" class="handle placeholder';if($r['status']=='delete'){$content.=' danger';}$content.='">';
							$content.='<td>'.$r['username'].'</td>';
							$content.='<td>'.$r['name'].'</td>';
							$content.='<td><a href="mailto:'.$r['email'].'">'.$r['email'].'</a></td>';
							$content.='<td>'.$r['rank'].'</td>';
							$content.='<td id="controls_'.$r['id'].'" class="text-right">';
								$content.='<a class="btn btn-primary btn-xs';if($r['status']=='delete'){$content.=' hidden';}$content.='" href="admin/accounts/edit/'.$r['id'].'">View</a> ';
								$content.='<button class="btn btn-primary btn-xs';if($r['status']!='delete'){$content.=' hidden';}$content.='" onclick="updateButtons(\''.$r['id'].'\',\'login\',\'status\',\'\')">Restore</button> ';
								$content.='<button class="btn btn-danger btn-xs';if($r['status']=='delete'){$content.=' hidden';}$content.='" onclick="updateButtons(\''.$r['id'].'\',\'login\',\'status\',\'delete\')">Delete</button> ';
			if($user['rank']>900){
								$content.='<button class="btn btn-warning btn-xs';if($r['status']!='delete'){$content.=' hidden';}$content.='" onclick="purge(\''.$r['id'].'\',\'login\')">Purge</button>';
			}
							$content.='</td>';
							$content.='<td class="hidden">'.$r['notes'].'</td>';
						$content.='</tr>';
		}
					$content.='</tbody>';
				$content.='</table>';
			$content.='</div>';
	}
}else{
	include'includes/noaccess.php';
}
		$content.='</div>';
	$content.='</div>';
$content.='</main>';
