<?php
$content.='<main id="content" class="libr8-col-md-12">';
if($args[0]=="confirm"){
	include"includes/add_order.php";
}else{
	$total=0;
	$s=$db->prepare("SELECT * FROM cart WHERE si=:si ORDER BY ti DESC");
	$s->execute(array(':si'=>SESSIONID));
	if($s->rowCount()>0){
	$content.='<div class="libr8-panel panel-default">';
		$content.='<div class="libr8-panel-body">';
			$content.='<div class="libr8-invoice libr8-table-responsive">';
				$content.='<table class="libr8-table libr8-table-striped libr8-table-condensed">';
					$content.='<thead>';
						$content.='<tr>';
							$content.='<th>Code</th>';
							$content.='<th>Title</th>';
							$content.='<th class="libr8-text-center libr8-col-sm-1">Quantity</th>';
							$content.='<th class="libr8-col-md-1 libr8-text-center">Cost</th>';
							$content.='<th class="libr8-col-md-2 libr8-text-right">Total</th>';
							$content.='<th class="libr8-col-sm-1"></th>';
						$content.='</tr>';
					$content.='</thead>';
					$content.='<tbody id="updateorder">';
	while($oi=$s->fetch(PDO::FETCH_ASSOC)){
		$si=$db->prepare("SELECT * FROM content WHERE id=:id");
		$si->execute(array(':id'=>$oi['iid']));
		$i=$si->fetch(PDO::FETCH_ASSOC);
					$content.='<tr>';
						$content.='<td class="libr8-text-left">'.$i['code'].'</td>';
						$content.='<td class="libr8-text-left">'.$i['title'].'</td>';
						$content.='<td class="libr8-text-center">';
							$content.='<form target="sp" action="includes/update.php">';
								$content.='<input type="hidden" name="id" value="'.$oi['id'].'">';
								$content.='<input type="hidden" name="t" value="cart">';
								$content.='<input type="hidden" name="c" value="quantity">';
								$content.='<input class="libr8-form-control text-center" name="da" value="'.$oi['quantity'].'">';
							$content.='</form>';
						$content.='</td>';
						$content.='<td class="libr8-col-md-1 libr8-text-right">';
							$content.='<input class="libr8-form-control libr8-text-center" value="'.$oi['cost'].'" readonly>';
						$content.='</td>';
						$content.='<td class="libr8-text-right">'.$oi['cost']*$oi['quantity'].'</td>';
						$content.='<td class="libr8-text-right">';
							$content.='<button class="libr8-btn libr8-btn-danger" onclick="$(\'#sp\').load(\'includes/update.php?id='.$oi['id'].'&t=cart&c=quantity&da=0\');"><i class="fa fa-trash"></i></button>';
						$content.='</td>';
					$content.='</tr>';
		$total=$total+($oi['cost']*$oi['quantity']);
	}
					$content.='<tr>';
						$content.='<td colspan="3">&nbsp;</td>';
						$content.='<td class="libr8-text-right"><strong>Total</strong></td>';
						$content.='<td class="libr8-text-right"><strong>';$total=$total+$oi['postagecost'];$content.=$total.'</strong></td>';
						$content.='<td></td>';
					$content.='</tr>';
				$content.='</tbody>';
				$content.='<tfoot>';
					$content.='<tr>';
						$content.='<td colspan="6"><small class="libr8-text-muted">Enter \'0\' as the Quantity to remove items</small></td>';
					$content.='</tr>';
				$content.='</tfoot>';
			$content.='</table>';
		$content.='</div>';
	$content.='</div>';
$content.='</div>';
$content.='<div class="libr8-panel libr8-panel-default">';
	$content.='<div class="libr8-panel-heading">';
		$content.='<h3 class="libr8-panel-title">Create or Add to Existing Account</h3>';
	$content.='</div>';
	$content.='<div class="libr8-panel-body">';
		$content.='<form method="post" action="cart/confirm">';
			$content.='<div class="libr8-form-group">';
				$content.='<label class="libr8-control-label libr8-col-sm-2">&nbsp;</label>';
				$content.='<div class="libr8-input-group libr8-col-sm-10 libr8-text-danger">Highlighted Fields are Required</div>';
			$content.='</div>';
			$content.='<div class="libr8-form-group">';
				$content.='<label for="email" class="libr8-control-label libr8-col-md-2 libr8-col-xs-4 libr8-text-danger">Email</label>';
				$content.='<div class="libr8-input-group libr8-col-md-10 libr8-col-xs-8 libr8-has-error">';
					$content.='<input type="text" id="email" class="libr8-form-control" name="email" value="" placeholder="Enter an Email" required>';
					$content.='<div class="libr8-input-group-btn">';
						$content.='<button class="libr8-btn libr8-btn-default" onclick="getClient($(\'#email\').val());return false">Retrieve</button>';
					$content.='</div>';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="libr8-form-group">';
				$content.='<label for="business" class="libr8-control-label libr8-col-md-2 libr8-col-xs-4">Business</label>';
				$content.='<div class="libr8-input-group libr8-col-md-10 libr8-col-xs-8">';
					$content.='<input type="text" id="business" class="libr8-form-control" name="business" value="" placeholder="Enter a Business...">';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="libr8-form-group">';
				$content.='<label for="address" class="libr8-control-label libr8-col-md-2 libr8-col-xs-4">Address</label>';
				$content.='<div class="libr8-input-group libr8-col-md-10 libr8-col-xs-8">';
					$content.='<input type="text" id="address" class="libr8-form-control" name="address" value="" placeholder="Enter an Address...">';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="libr8-form-group">';
				$content.='<label for="suburb" class="libr8-control-label libr8-col-md-2 libr8-col-xs-4">Suburb</label>';
				$content.='<div class="libr8-input-group libr8-col-md-10 libr8-col-xs-8">';
					$content.='<input type="text" id="suburb" class="libr8-form-control" name="suburb" value="" placeholder="Enter a Suburb...">';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="libr8-form-group">';
				$content.='<label for="city" class="libr8-control-label libr8-col-md-2 libr8-col-xs-4">City</label>';
				$content.='<div class="libr8-input-group libr8-col-md-10 libr8-col-xs-8">';
					$content.='<input type="text" id="city" class="libr8-form-control" name="city" value="" placeholder="Enter a City...">';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="libr8-form-group">';
				$content.='<label for="state" class="libr8-control-label libr8-col-md-2 libr8-col-xs-4">State</label>';
				$content.='<div class="libr8-input-group libr8-col-md-10 libr8-col-xs-8">';
					$content.='<input type="text" id="state" class="libr8-form-control" name="state" value="" placeholder="Enter a State...">';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="libr8-form-group">';
				$content.='<label for="postcode" class="libr8-control-label libr8-col-md-2 libr8-col-xs-4">Postcode</label>';
				$content.='<div class="libr8-input-group libr8-col-md-10 libr8-col-xs-8">';
					$content.='<input type="text" id="postcode" class="libr8-form-control" name="postcode" value="" placeholder="Enter a Postcode...">';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="libr8-form-group">';
				$content.='<label for="phone" class="libr8-control-label libr8-col-md-2 libr8-col-xs-4">Phone</label>';
				$content.='<div class="libr8-input-group libr8-col-md-10 libr8-col-xs-8">';
					$content.='<input type="text" id="phone" class="libr8-form-control" name="phone" value="" placeholder="Enter a Phone Number...">';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="libr8-pull-right">';
				$content.='<button class="libr8-btn libr8-btn-success">Confirm Order</button>';
			$content.='</div>';
		$content.='</form>';
	$content.='</div>';
$content.='</div>';
	}else{
	$content.='<div class="libr8-alert libr8-alert-info">You don\'t have any Items in the Cart</div>';
	}
}
$content.='</main>';
