<?php
$content.='<main id="content" class="col-md-12">';
if($args[0]=="confirm"){
	include"includes/add_order.php";
}else{
	$total=0;
	$s=$db->prepare("SELECT * FROM cart WHERE si=:si ORDER BY ti DESC");
	$s->execute(array(':si'=>SESSIONID));
	if($s->rowCount()>0){
	$content.='<div class="panel panel-default">';
		$content.='<div class="panel-body">';
			$content.='<div class="invoice table-responsive">';
				$content.='<table class="table table-striped table-condensed">';
					$content.='<thead>';
						$content.='<tr>';
							$content.='<th>Code</th>';
							$content.='<th>Title</th>';
							$content.='<th class="text-center col-sm-1">Quantity</th>';
							$content.='<th class="col-md-1 text-center">Cost</th>';
							$content.='<th class="col-md-2 text-right">Total</th>';
							$content.='<th class="col-sm-1"></th>';
						$content.='</tr>';
					$content.='</thead>';
					$content.='<tbody id="updateorder">';
	while($oi=$s->fetch(PDO::FETCH_ASSOC)){
			$si=$db->prepare("SELECT * FROM content WHERE id=:id");
			$si->execute(array(':id'=>$oi['iid']));
			$i=$si->fetch(PDO::FETCH_ASSOC);
						$content.='<tr>';
							$content.='<td class="text-left">'.$i['code'].'</td>';
							$content.='<td class="text-left">'.$i['title'].'</td>';
							$content.='<td class="text-center">';
								$content.='<form target="sp" action="includes/update.php">';
									$content.='<input type="hidden" name="id" value="'.$oi['id'].'">';
									$content.='<input type="hidden" name="t" value="cart">';
									$content.='<input type="hidden" name="c" value="quantity">';
									$content.='<input class="form-control text-center" name="da" value="'.$oi['quantity'].'">';
								$content.='</form>';
							$content.='</td>';
							$content.='<td class="col-md-1 text-right">';
								$content.='<input class="form-control text-center" value="'.$oi['cost'].'" readonly>';
							$content.='</td>';
							$content.='<td class="text-right">'.$oi['cost']*$oi['quantity'].'</td>';
							$content.='<td class="text-right">';
								$content.='<button class="btn btn-danger" onclick="$(\'#sp\').load(\'includes/update.php?id='.$oi['id'].'&t=cart&c=quantity&da=0\');"><i class="fa fa-trash"></i></button>';
							$content.='</td>';
						$content.='</tr>';
		$total=$total+($oi['cost']*$oi['quantity']);
	}
						$content.='<tr>';
							$content.='<td colspan="3">&nbsp;</td>';
							$content.='<td class="text-right"><strong>Total</strong></td>';
							$content.='<td class="text-right"><strong>';$total=$total+$oi['postagecost'];$content.=$total.'</strong></td>';
							$content.='<td></td>';
						$content.='</tr>';
					$content.='</tbody>';
					$content.='<tfoot>';
						$content.='<tr>';
							$content.='<td colspan="6"><small class="text-muted">Enter \'0\' as the Quantity to remove items</small></td>';
						$content.='</tr>';
					$content.='</tfoot>';
				$content.='</table>';
			$content.='</div>';
		$content.='</div>';
	$content.='</div>';
	$content.='<div class="panel panel-default">';
		$content.='<div class="panel-heading">';
			$content.='<h3 class="panel-title">Create or Add to Existing Account</h3>';
		$content.='</div>';
		$content.='<div class="panel-body">';
			$content.='<form method="post" action="cart/confirm">';
				$content.='<div class="form-group">';
					$content.='<label class="control-label col-sm-2">&nbsp;</label>';
					$content.='<div class="input-group col-sm-10 text-danger">Highlighted Fields are Required</div>';
				$content.='</div>';
				$content.='<div class="form-group">';
					$content.='<label for="email" class="control-label col-md-2 col-xs-4 text-danger">Email</label>';
					$content.='<div class="input-group col-md-10 col-xs-8 has-error">';
						$content.='<input type="text" id="email" class="form-control" name="email" value="" placeholder="Enter an Email" required>';
						$content.='<div class="input-group-btn">';
							$content.='<button class="btn btn-default" onclick="getClient($(\'#email\').val());return false">Retrieve</button>';
						$content.='</div>';
					$content.='</div>';
				$content.='</div>';
				$content.='<div class="form-group">';
					$content.='<label for="business" class="control-label col-md-2 col-xs-4">Business</label>';
					$content.='<div class="input-group col-md-10 col-xs-8">';
						$content.='<input type="text" id="business" class="form-control" name="business" value="" placeholder="Enter a Business...">';
					$content.='</div>';
				$content.='</div>';
				$content.='<div class="form-group">';
					$content.='<label for="address" class="control-label col-md-2 col-xs-4">Address</label>';
					$content.='<div class="input-group col-md-10 col-xs-8">';
						$content.='<input type="text" id="address" class="form-control" name="address" value="" placeholder="Enter an Address...">';
					$content.='</div>';
				$content.='</div>';
				$content.='<div class="form-group">';
					$content.='<label for="suburb" class="control-label col-md-2 col-xs-4">Suburb</label>';
					$content.='<div class="input-group col-md-10 col-xs-8">';
						$content.='<input type="text" id="suburb" class="form-control" name="suburb" value="" placeholder="Enter a Suburb...">';
					$content.='</div>';
				$content.='</div>';
				$content.='<div class="form-group">';
					$content.='<label for="city" class="control-label col-md-2 col-xs-4">City</label>';
					$content.='<div class="input-group col-md-10 col-xs-8">';
						$content.='<input type="text" id="city" class="form-control" name="city" value="" placeholder="Enter a City...">';
					$content.='</div>';
				$content.='</div>';
				$content.='<div class="form-group">';
					$content.='<label for="state" class="control-label col-md-2 col-xs-4">State</label>';
					$content.='<div class="input-group col-md-10 col-xs-8">';
						$content.='<input type="text" id="state" class="form-control" name="state" value="" placeholder="Enter a State...">';
					$content.='</div>';
				$content.='</div>';
				$content.='<div class="form-group">';
					$content.='<label for="postcode" class="control-label col-md-2 col-xs-4">Postcode</label>';
					$content.='<div class="input-group col-md-10 col-xs-8">';
						$content.='<input type="text" id="postcode" class="form-control" name="postcode" value="" placeholder="Enter a Postcode...">';
					$content.='</div>';
				$content.='</div>';
				$content.='<div class="form-group">';
					$content.='<label for="phone" class="control-label col-md-2 col-xs-4">Phone</label>';
					$content.='<div class="input-group col-md-10 col-xs-8">';
						$content.='<input type="text" id="phone" class="form-control" name="phone" value="" placeholder="Enter a Phone Number...">';
					$content.='</div>';
				$content.='</div>';
				$content.='<div class="pull-right">';
					$content.='<button class="btn btn-success">Confirm Order</button>';
				$content.='</div>';
			$content.='</form>';
		$content.='</div>';
	$content.='</div>';
	}else{
	$content.='<div class="alert alert-info">You don\'t have any Items in the Cart</div>';
	}
}
$content.='</main>';
