<?php
$foot.='<div id="login" class="modal fade" tabindex="-1" aria-hidden="true">';
if($config['options']{2}==1){
$foot.='<div class="modal-dialog">';
	$foot.='<div class="modal-content col-md-9">';
		$foot.='<div class="modal-header">';
			$foot.='<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>';
			$foot.='<h4 class="modal-title">Login</h4>';
		$foot.='</div>';
		$foot.='<div class="modal-body">';
			$foot.='<form method="post" action="" accept-charset="UTF-8">';
				$foot.='<input type="hidden" name="act" value="login">';
				$foot.='<div class="form-group">';
					$foot.='<label for="username" class="control-label col-md-3 col-xs-3">Username</label>';
					$foot.='<div class="input-group col-sm-8 col-xs-9">';
						$foot.='<input type="text" id="username" class="form-control" name="username" value="" placeholder="Enter a Username..." autofocus>';
					$foot.='</div>';
				$foot.='</div>';
				$foot.='<div class="form-group">';
					$foot.='<label for="password" class="control-label col-md-3 col-xs-3">Password</label>';
					$foot.='<div class="input-group col-md-8 col-xs-9">';
						$foot.='<input type="password" id="password" class="form-control" name="password" placeholder="Enter a Password..." autocomplete="off">';
					$foot.='</div>';
				$foot.='</div>';
				$foot.='<div class="form-group">';
					$foot.='<label class="control-label col-md-3 col-xs-3">&nbsp;</label>';
					$foot.='<div class="input-group col-md-8 col-xs-9">';
						$foot.='<button class="btn btn-success btn-block">Login</button>';
					$foot.='</div>';
				$foot.='</div>';
			$foot.='</form>';
			$foot.='<div class="form-group">';
				$foot.='<div class="input-group col-md-11 col-xs-12 text-right">';
					$foot.='<a href="recover">Forgot Password?</a>';
				$foot.='</div>';
			$foot.='</div>';
		$foot.='</div>';
if($config['options']{3}==1){
		$foot.='<div class="modal-header">';
			$foot.='<h4 class="modal-title">Sign Up</h4>';
		$foot.='</div>';
		$foot.='<div class="modal-body">';
			$foot.='<form method="post" action="newaccount" accept-charset="UTF-8">';
				$foot.='<input type="hidden" name="act" value="newaccount">';
				$foot.='<div class="form-group">';
					$foot.='<label for="email" class="control-label col-md-3 col-xs-3">Email</label>';
					$foot.='<div class="input-group col-sm-8 col-xs-9">';
						$foot.='<input type="text" id="email" class="form-control" name="email" value="" placeholder="Enter an Email...">';
					$foot.='</div>';
				$foot.='</div>';
				$foot.='<div class="form-group">';
					$foot.='<label for="username" class="control-label col-sm-3 col-xs-3">Username</label>';
					$foot.='<div class="input-group col-sm-8 col-xs-9">';
						$foot.='<input type="text" id="username" class="form-control" name="username" placeholder="Enter a Username...">';
					$foot.='</div>';
				$foot.='</div>';
				$foot.='<div class="form-group">';
					$foot.='<label class="control-label col-sm-3 col-xs-3"></label>';
					$foot.='<div class="input-group col-sm-8 col-xs-9">';
                        $foot.='<button class="btn btn-success btn-block">Sign Up</button>';
					$foot.='</div>';
				$foot.='</div>';
			$foot.='</form>';
		$foot.='</div>';
    }
		$foot.='<div class="modal-footer"></div>';
	$foot.='</div>';
$foot.='</div>';
}else{
$foot.='<main class="content">';
	$foot.='<div class="thumbnail item col-md-6">';
		$foot.='<div class="panel-body">';
			$foot.='<h4>Login</h4>';
			$foot.='<form method="post" action="" accept-charset="UTF-8">';
				$foot.='<input type="hidden" name="act" value="login">';
				$foot.='<div class="form-group">';
					$foot.='<label for="username" class="control-label col-sm-4 col-xs-4">Username</label>';
					$foot.='<div class="input-group col-sm-8 col-xs-8">';
						$foot.='<input type="text" id="username" class="form-control" name="username" value="<?php echo$usr;?>" placeholder="Enter a Username..." autofocus>';
					$foot.='</div>';
				$foot.='</div>';
				$foot.='<div class="form-group">';
					$foot.='<label for="password" class="control-label col-sm-4 col-xs-4">Password</label>';
					$foot.='<div class="input-group col-sm-8 col-xs-8">';
						$foot.='<input type="password" id="password" class="form-control" name="password" placeholder="Enter a Password..." autocomplete="off">';
					$foot.='</div>';
				$foot.='</div>';
				$foot.='<div class="form-group">';
					$foot.='<label class="control-label col-sm-4 col-xs-4">&nbsp;</label>';
					$foot.='<div class="input-group col-sm-8 col-xs-8">';
						$foot.='<button class="btn btn-success btn-large btn-block">Login</button>';
					$foot.='</div>';
				$foot.='</div>';
			$foot.='</form>';
			$foot.='<div class="pull-right">';
				$foot.='<a href="recover">Forgot Password?</a>';
			$foot.='</div>';
		$foot.='</div>';
	$foot.='</div>';
if($config[options]{3}==1){
	$foot.='<div class="thumbnail item col-md-6">';
		$foot.='<div class="panel-body">';
			$foot.='<h4>Sign Up</h4>';
			$foot.='<form method="post" action="newaccount" accept-charset="UTF-8">';
				$foot.='<input type="hidden" name="act" value="newaccount">';
				$foot.='<div class="form-group">';
					$foot.='<label for="email" class="control-label col-sm-4 col-xs-4">Email</label>';
					$foot.='<div class="input-group col-sm-8 col-xs-8">';
						$foot.='<input type="text" id="email" class="form-control" name="email" value="" placeholder="Enter an Email...">';
					$foot.='</div>';
				$foot.='</div>';
				$foot.='<div class="form-group">';
					$foot.='<label for="username" class="control-label col-sm-4 col-xs-4">Username</label>';
					$foot.='<div class="input-group col-sm-8 col-xs-8">';
						$foot.='<input type="text" id="username" class="form-control" name="username" placeholder="Enter a Username...">';
					$foot.='</div>';
				$foot.='</div>';
				$foot.='<div class="form-group">';
					$foot.='<label class="control-label col-sm-4 col-xs-4"></label>';
					$foot.='<div class="input-group col-sm-8 col-xs-8">';
						$foot.='<button class="btn btn-success btn-large btn-block">Sign Up</button>';
					$foot.='</div>';
				$foot.='</div>';
			$foot.='</form>';
		$foot.='</div>';
	$foot.='</div>';
}
$foot.='</main>';
}
$foot.='</div>';
