<?php
$content.='<main id="content" class="libr8-col-md-12"><div class="libr8-panel libr8-panel-default"><div class="libr8-panel-body">';
if($user['rank']>899){
	$content.='<ul class="libr8-nav libr8-nav-tabs">';
		$content.='<li class="libr8-active"><a href="#theme" data-toggle="tab">Theme</a></li>';
		$content.='<li><a href="#home" data-toggle="tab">Pages</a></li>';
		$content.='<li><a href="#contact" data-toggle="tab">Contact</a></li>';
		$content.='<li><a href="#interface" data-toggle="tab">Interface</a></li>';
		$content.='<li><a href="#banking" data-toggle="tab">Banking</a></li>';
		$content.='<li><a href="#seo" data-toggle="tab">SEO</a></li>';
		$content.='<li><a href="#security" data-toggle="tab">Security</a></li>';
	$content.='</ul>';
	$content.='<div class="libr8-tab-content">';
		$content.='<div id="theme" class="libr8-tab-pane libr8-fade libr8-in libr8-active">';
			$content.='<div class="libr8-row libr8-form-group libr8-theme-chooser">';
	foreach(new DirectoryIterator('layout') as $folder){
		if($folder->isDOT())continue;
		if($folder->isDir()){
			$theme=parse_ini_file('layout/'.$folder.'/theme.ini',true);
				$content.='<div class="libr8-col-xs-12 libr8-col-sm-12 libr8-col-md-4 libr8-col-lg-4">';
					$content.='<div class="libr8-theme-chooser-item';
            if($config['theme']==$folder){$content.=' libr8-selected';}
            $content.='" data-theme="'.$folder.'"><img src="';
            if(file_exists('layout/'.$folder.'/theme.jpg')){
                $content.='layout/'.$folder.'/theme.jpg';
            }elseif(file_exists('layout/'.$folder.'/theme.png')){
                $content.='layout/'.$folder.'/theme.png';
            }else{
                $content.='images/noimage.jpg';
            }
					$content.='" class="libr8-img-rounded libr8-col-xs-4 libr8-col-sm-4 libr8-col-md-12 libr8-col-lg-12" alt="'.$theme['title'].'">';
						$content.='<div class="libr8-col-xs-8 libr8-col-sm-8 libr8-col-md-12 libr8-col-lg-12">';
							$content.='<span class="libr8-title">'.$theme['title'].'</span>';
							$content.='<small class="libr8-version">Version: v'.$theme['version'].'</small>';
							$content.='<small class="libr8-creator">Creator: <a target="_blank" href="'.$theme['creator_url'].'">'.$theme['creator'].'</a></small>';
							$content.='<small class="libr8-description">'.$theme['description'].'</small>';
						$content.='</div>';
						$content.='<div class="libr8-clear"></div>';
					$content.='</div>';
				$content.='</div>';
		}
	}
			$content.='</div>';
		$content.='</div>';
	$content.='<div id="home" class="libr8-tab-pane libr8-fade libr8-in">';
	$s=$db->query("SELECT * FROM menu ORDER BY menu DESC, ord ASC");
	while($r=$s->fetch(PDO::FETCH_ASSOC)){
        $content.='<div class="libr8-well">';
			$content.='<h4 onclick="$(\'#menu'.$r['id'].'\').toggle(400);">'.$r['title'].'</h4>';
			$content.='<div id="menu'.$r['id'].'" style="display:none">';
				$content.='<div class="libr8-form-group">';
					$content.='<label for="menu'.$r['id'].'" class="libr8-control-label libr8-col-lg-2 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">Active</label>';
					$content.='<div class="libr8-input-group libr8-col-lg-10 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
						$content.='<input type="checkbox" id="menu'.$r['id'].'" data-dbid="'.$r['id'].'" data-dbt="menu" data-dbc="active" data-dbb="0"';if($r['active']==1){$content.=' checked';}$content.='>';
					$content.='</div>';
				$content.='</div>';
				$content.='<div class="libr8-form-group">';
					$content.='<label for="seoTitle" class="libr8-control-label libr8-col-lg-2 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">Menu</label>';
					$content.='<div class="libr8-input-group libr8-col-lg-10 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
						$content.='<select class="libr8-form-control" onchange="update(\''.$r['id'].'\',\'menu\',\'menu\',$(this).val());">';
							$content.='<option value="head"';if($r['menu']=='head'){$content.=' selected';}$content.='>Header</option>';
							$content.='<option value="footer"';if($r['menu']=='footer'){$content.=' selected';}$content.='>Footer</option>';
						$content.='</select>';
					$content.='</div>';
				$content.='</div>';
				$content.='<div class="libr8-form-group">';
					$content.='<label for="seoTitle" class="libr8-control-label libr8-col-lg-2 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">seoTitle</label>';
					$content.='<div class="libr8-input-group libr8-col-lg-10 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
						$content.='<input type="text" id="seoTitle" class="libr8-form-control textinput" value="'.$r['seoTitle'].'" data-dbid="'.$r['id'].'" data-dbt="menu" data-dbc="seoTitle" placeholder="Enter a Page Title...">';
						$content.='<div id="seoTitlesave" class="libr8-input-group-btn libr8-hidden">';
							$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
						$content.='</div>';
					$content.='</div>';
				$content.='</div>';
				$content.='<div class="libr8-form-group">';
					$content.='<label for="seoCaption" class="libr8-control-label libr8-col-lg-2 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">seoCaption</label>';
					$content.='<div class="libr8-input-group libr8-col-lg-10 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
						$content.='<input type="text" id="seoCaption" class="libr8-form-control libr8-textinput" value="'.$r['seoCaption'].'" data-dbid="'.$r['id'].'" data-dbt="menu" data-dbc="seoCaption" placeholder="Enter a Page Caption...">';
						$content.='<div id="seoCaptionsave" class="libr8-input-group-btn libr8-hidden">';
							$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
						$content.='</div>';
					$content.='</div>';
				$content.='</div>';
				$content.='<div class="libr8-form-group">';
					$content.='<label for="seoDescription" class="libr8-control-label libr8-col-lg-2 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">seoDescription</label>';
					$content.='<div class="libr8-input-group libr8-col-lg-10 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
						$content.='<input type="text" id="seoDescription" class="libr8-form-control textinput" value="'.$r['seoDescription'].'" data-dbid="'.$r['id'].'" data-dbt="menu" data-dbc="seoDescription" placeholder="Enter a Page Description...">';
						$content.='<div id="seoDescriptionsave" class="libr8-input-group-btn libr8-hidden">';
							$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
						$content.='</div>';
					$content.='</div>';
				$content.='</div>';
				$content.='<div class="libr8-form-group">';
					$content.='<label for="seoKeywords" class="libr8-control-label libr8-col-lg-2 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">seoKeywords</label>';
					$content.='<div class="libr8-input-group libr8-col-lg-10 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
						$content.='<input type="text" id="seoKeywords" class="libr8-form-control libr8-textinput" value="'.$r['seoKeywords'].'" data-dbid="'.$r['id'].'" data-dbt="menu" data-dbc="seoKeywords" placeholder="Enter Page Keywords...">';
						$content.='<div id="seoKeywordssave" class="libr8-input-group-btn libr8-hidden">';
							$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
						$content.='</div>';
					$content.='</div>';
				$content.='</div>';
			$content.='</div>';
		$content.='</div>';
	}
    $content.='</div>';
    $content.='<div id="contact" class="libr8-tab-pane libr8-fade">';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="options18" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4 libr8-text-right">';
				$content.='<input type="checkbox" id="options18" data-dbid="1" data-dbt="config" data-dbc="options" data-dbb="18"';if($config['options']{1}==1){$content.=' checked';}$content.='>';
			$content.='</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">Display Address and Phone Numbers on Contact Us Page</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="business" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">Business</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
				$content.='<input type="text" id="business" class="libr8-form-control libr8-textinput" value="'.$config['business'].'" data-dbid="1" data-dbt="config" data-dbc="business" placeholder="Enter Business Name...">';
				$content.='<div id="businesssave" class="libr8-input-group-btn libr8-hidden">';
					$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
				$content.='</div>';
			$content.='</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="abn" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">ABN</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
				$content.='<input type="text" id="abn" class="libr8-form-control libr8-textinput" value="'.$config['abn'].'" data-dbid="1" data-dbt="config" data-dbc="abn" placeholder="Enter an ABN...">';
				$content.='<div id="abnsave" class="libr8-input-group-btn libr8-hidden">';
					$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
				$content.='</div>';
			$content.='</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="email" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">Email</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
				$content.='<input type="text" id="email" class="libr8-form-control libr8-textinput" value="'.$config['email'].'" data-dbid="1" data-dbt="config" data-dbc="email" placeholder="Enter an Email...">';
				$content.='<div id="emailsave" class="libr8-input-group-btn libr8-hidden">';
					$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
				$content.='</div>';
			$content.='</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="options0" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4 text-right">';
				$content.='<input type="checkbox" id="options0" data-dbid="1" data-dbt="config" data-dbc="options" data-dbb="0"';if($config['options']{0}==1){$content.=' checked';}$content.='>';
			$content.='</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">Display Phone and Mobile Numbers</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="phone" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">Phone</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
				$content.='<input type="text" id="phone" class="libr8-form-control textinput" value="'.$config['phone'].'" data-dbid="1" data-dbt="config" data-dbc="phone" placeholder="Enter a Phone Number...">';
				$content.='<div id="phonesave" class="libr8-input-group-btn libr8-hidden">';
					$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
				$content.='</div>';
			$content.='</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="mobile" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">Mobile</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8"><input type="text" id="mobile" class="libr8-form-control textinput" value="'.$config['mobile'].'" data-dbid="1" data-dbt="config" data-dbc="mobile" placeholder="Enter a Mobile Number...">';
			$content.='<div id="mobilesave" class="libr8-input-group-btn libr8-hidden">';
				$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button></div>';
			$content.='</div>';
		$content.='</div>';
		$content.='<div class="libr8-well">';
			$content.='<h4>Google Maps</h4>';
			$content.='<div class="libr8-form-group">';
				$content.='<label for="geoLocation" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">GEO Location</label>';
				$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
					$content.='<input type="text" id="geoLocation" class="libr8-form-control libr8-textinput" value="'.$config['geoLocation'].'" data-dbid="1" data-dbt="config" data-dbc="geoLocation" placeholder="Enter a GEO Location">';
					$content.='<div id="geoLocationsave" class="libr8-input-group-btn libr8-hidden">';
						$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
					$content.='</div>';
				$content.='</div>';
			$content.='</div>';
			$content.='<div class="libr8-form-group">';
				$content.='<label for="geoReference" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">Map Reference</label>';
				$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
					$content.='<input type="text" id="geoReference" class="libr8-form-control textinput" value="'.$config['geoReference'].'" data-dbid="1" data-dbt="config" data-dbc="geoReference" placeholder="Enter a Map Reference...">';
					$content.='<div id="geoReferencesave" class="libr8-input-group-btn libr8-hidden">';
						$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
					$content.='</div>';
				$content.='</div>';
			$content.='</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="options1" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4 libr8-text-right">';
				$content.='<input type="checkbox" id="options1" data-dbid="1" data-dbt="config" data-dbc="options" data-dbb="1"';if($config['options']{1}==1){$content.=' checked';}$content.='>';
			$content.='</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">Display Address on Site</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="address" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">Address</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
				$content.='<input type="text" id="address" class="libr8-form-control textinput" value="'.$config['address'].'" data-dbid="1" data-dbt="config" data-dbc="address" placeholder="Enter an Address...">';
				$content.='<div id="addresssave" class="libr8-input-group-btn libr8-hidden">';
					$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
				$content.='</div>';
			$content.='</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">Suburb</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
				$content.='<input type="text" id="suburb" class="libr8-form-control textinput" value="'.$config['suburb'].'" data-dbid="1" data-dbt="config" data-dbc="suburb" placeholder="Enter a Suburb...">';
				$content.='<div id="suburbsave" class="libr8-input-group-btn libr8-hidden">';
					$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
				$content.='</div>';
			$content.='</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="city" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">City</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
				$content.='<input type="text" id="city" class="libr8-form-control libr8-textinput" value="'.$config['city'].'" data-dbid="1" data-dbt="config" data-dbc="city" placeholder="Enter a City...">';
				$content.='<div id="citysave" class="libr8-input-group-btn libr8-hidden">';
					$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
				$content.='</div>';
			$content.='</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="state" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">State</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
				$content.='<input type="text" id="state" class="libr8-form-control libr8-textinput" value="'.$config['state'].'" data-dbid="1" data-dbt="config" data-dbc="state" placeholder="Enter a State...">';
				$content.='<div id="statesave" class="libr8-input-group-btn libr8-hidden">';
					$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
				$content.='</div>';
			$content.='</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="postcode" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">Postcode</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
				$content.='<input type="text" id="postcode" class="libr8-form-control libr8-textinput" value="';if($config['postcode']!=0){$content.=$config['postcode'];}$content.='" data-dbid="1" data-dbt="config" data-dbc="postcode" placeholder="Enter a Postcode...">';
				$content.='<div id="postcodesave" class="libr8-input-group-btn libr8-hidden">';
					$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
				$content.='</div>';
			$content.='</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="country" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">Country</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
				$content.='<input type="text" id="country" class="libr8-form-control libr8-textinput" value="'.$config['country'].'" data-dbid="1" data-dbt="config" data-dbc="country" placeholder="Enter a Country...">';
				$content.='<div id="countrysave" class="libr8-input-group-btn libr8-hidden">';
					$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
				$content.='</div>';
			$content.='</div>';
		$content.='</div>';
	$content.='</div>';
	$content.='<div id="interface" class="libr8-tab-pane libr8-fade">';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="login_type" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">Login Type</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
				$content.='<select id="login_type" class="libr8-form-control" onchange="update(\'1\',\'config\',\'login_type\',$(this).val());">';
					$content.='<option value="1"';if($config['options']{2}==1){$content.=' selected';}$content.='>Modal</option>';
					$content.='<option value="0"';if($config['options']{2}==0){$content.=' selected';}$content.='>Page</option>';
				$content.='</select>';
			$content.='</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="options26" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4 libr8-text-right">';
				$content.='<input type="checkbox" id="options26" data-dbid="1" data-dbt="config" data-dbc="options" data-dbb="3"';if($config['options']{3}==1){$content.=' checked';}$content.='>';
			$content.='</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">Enable Account Sign Ups</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="tooltips" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4 libr8-text-right">';
				$content.='<input type="checkbox" id="tooltips0" data-dbid="1" data-dbt="config" data-dbc="tooltips" data-dbb="4"';if($config['options']{4}==1){$content.=' checked';}$content.='>';
			$content.='</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">Enable Tooltips</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="timezone" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">Timezone</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
				$content.='<select id="timezone" class="libr8-form-control" onchange="update(\'1\',\'config\',\'timezone\',$(this).val());">';
    function formatOffset($offset){
        $hours=$offset/3600;
        $remainder=$offset%3600;
        $sign=$hours>0?'+':'-';
        $hour=(int)abs($hours);
        $minutes=(int)abs($remainder/60);
        if($hour==0&&$minutes==0)$sign=' ';
        return$sign.str_pad($hour,2,'0',STR_PAD_LEFT).':'.str_pad($minutes,2,'0');
    }
    $utc=new DateTimeZone('UTC');
    $dt=new DateTime('now',$utc);
    foreach(DateTimeZone::listIdentifiers() as$tz){
        $current_tz=new DateTimeZone($tz);
        $offset=$current_tz->getOffset($dt);
        $transition=$current_tz->getTransitions($dt->getTimestamp(),$dt->getTimestamp());
        $abbr=$transition[0]['abbr'];
        $content.='<option value="'.$tz.'"';
        if($tz==$config['timezone']){$content.=' selected';}
        $content.='>'.$tz.' ['.$abbr.' '.formatOffset($offset).']</option>';
    }
				$content.='</select>';
			$content.='</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="dateFormat" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">DateFormat</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
				$content.='<input type="text" id="dateFormat" class="libr8-form-control textinput" value="'.$config['dateFormat'].'" data-dbid="1" data-dbt="config" data-dbc="dateFormat" placeholder="Enter a Date Format...">';
				$content.='<div id="dateFormatsave" class="libr8-input-group-btn libr8-hidden">';
					$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
				$content.='</div>';
			$content.='</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">&nbsp;</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
				$content.='<div class="libr8-well">';
					$content.='<h4 onclick="$(\'#dateTimeOptions\').toggle(400);">Show Date/Time Options</h4>';
					$content.='<table id="dateTimeOptions" class="libr8-table libr8-table-striped" style="display:none">';
						$content.='<thead>';
							$content.='<tr>';
								$content.='<th>format character</th>';
								$content.='<th>Description	Example</th>';
								$content.='<th>returned values</th>';
							$content.='</tr>';
						$content.='</thead>';
						$content.='<tbody>';
							$content.='<tr><td colspan="3" class="libr8-text-center"><strong>Day</strong></td></tr>';
							$content.='<tr><td>d</td><td>Day of the month, 2 digits with leading zeros</td><td>01 to 31</td></tr>';
							$content.='<tr><td>D</td><td>A textual representation of a day, three letters</td><td>Mon through Sun</td></tr>';
							$content.='<tr><td>j</td><td>Day of the month without leading zeros</td><td>1 to 31</td></tr>';
							$content.='<tr><td>l</td><td>A full textual representation of the day of the week</td><td>Sunday through Saturday</td></tr>';
							$content.='<tr><td>S</td><td>English ordinal suffix for the day of the month, 2 characters</td><td>st, nd, rd or th. Works well with j</td></tr>';
							$content.='<tr><td colspan="3" class="libr8-text-center"><strong>Month</strong></td></tr>';
							$content.='<tr><td>F</td><td>A full textual representation of a month, such as January or March</td><td>January through December</td></tr>';
							$content.='<tr><td>m</td><td>Numeric representation of a month, with leading zeros</td><td>01 through 12</td></tr>';
							$content.='<tr><td>M</td><td>A short textual representation of a month, three letters</td><td>Jan through Dec</td></tr>';
							$content.='<tr><td>n</td><td>Numeric representation of a month, without leading zeros</td><td>1 through 12</td></tr>';
							$content.='<tr><td colspan="3" class="libr8-text-center"><strong>Year</strong></td></tr>';
							$content.='<tr><td>L</td><td>Whether it\'s a leap year</td><td>1 if it is a leap year, 0 otherwise.</td></tr>';
							$content.='<tr><td>Y</td><td>A full numeric representation of a year, 4 digits</td><td>Examples: 1999 or 2003</td></tr>';
							$content.='<tr><td>y</td><td>A two digit representation of a year</td><td>Examples: 99 or 03</td></tr>';
							$content.='<tr><td colspan="3" class="libr8-text-center"><strong>Time</strong></td></tr>';
							$content.='<tr><td>a</td><td>Lowercase Ante meridiem and Post meridiem</td><td>am or pm</td></tr>';
							$content.='<tr><td>A</td><td>Uppercase Ante meridiem and Post meridiem</td><td>AM or PM</td></tr>';
							$content.='<tr><td>g</td><td>12-hour format of an hour without leading zeros</td><td>1 through 12</td></tr>';
							$content.='<tr><td>G</td><td>24-hour format of an hour without leading zeros</td><td>0 through 23</td></tr>';
							$content.='<tr><td>h</td><td>12-hour format of an hour with leading zeros</td><td>01 through 12</td></tr>';
							$content.='<tr><td>H</td><td>24-hour format of an hour with leading zeros</td><td>00 through 23</td></tr>';
							$content.='<tr><td>i</td><td>Minutes with leading zeros</td><td>00 to 59</td></tr>';
							$content.='<tr><td colspan="3" class="libr8-text-center"><strong>Timezone</strong></td></tr>';
							$content.='<tr><td>I</td><td>Whether or not the date is in daylight saving time</td><td>1 if Daylight Saving Time, 0 otherwise.</td></tr>';
							$content.='<tr><td colspan="3" class="libr8-text-center"><strong>Full Date/Time</strong></td></tr>';
							$content.='<tr><td>c</td><td>ISO 8601 date (added in PHP 5)</td><td>2004-02-12T15:19:21+00:00</td></tr>';
							$content.='<tr><td>r</td><td>RFC 2822 formatted date</td><td>Example: Thu, 21 Dec 2000 16:01:07 +0200</td></tr>';
						$content.='</tbody>';
					$content.='</table>';
				$content.='</div>';
			$content.='</div>';
		$content.='</div>';
	$content.='</div>';
	$content.='<div id="banking" class="libr8-tab-pane libr8-fade">';
		$content.='<h4>Banking Details</h4>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="bank" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">Bank</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
				$content.='<input type="text" id="bank" class="libr8-form-control libr8-textinput" value="'.$config['bank'].'" data-dbid="1" data-dbt="config" data-dbc="bank" placeholder="Enter Bank...">';
				$content.='<div id="banksave" class="libr8-input-group-btn libr8-hidden">';
					$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
				$content.='</div>';
			$content.='</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="bank_accname" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">Account Name</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
				$content.='<input type="text" id="bank_accname" class="libr8-form-control libr8-textinput" value="'.$config['bankAccountName'].'"data-dbid="1" data-dbt="config" data-dbc="bankAccountName" placeholder="Enter an Account Name...">';
				$content.='<div id="bank_accnamesave" class="libr8-input-group-btn libr8-hidden">';
					$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
				$content.='</div>';
			$content.='</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="bank_accnumber" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">Account Number</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
				$content.='<input type="text" id="bank_accnumber" class="libr8-form-control libr8-textinput" value="'.$config['bankAccountNumber'].'" data-dbid="1" data-dbt="config" data-dbc="bankAccountNumber" placeholder="Enter an Account Number...">';
				$content.='<div id="bank_accnumbersave" class="libr8-input-group-btn libr8-hidden">';
					$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
				$content.='</div>';
			$content.='</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="bank_bsb" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">BSB</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
				$content.='<input type="text" id="bank_bsb" class="libr8-form-control libr8-textinput" value="'.$config['bankBSB'].'" data-dbid="1" data-dbt="config" data-dbc="bankBSB" placeholder="Enter a BSB...">';
				$content.='<div id="bank_bsbsave" class="libr8-input-group-btn libr8-hidden">';
					$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
				$content.='</div>';
			$content.='</div>';
		$content.='</div>';
		$content.='<h4>PayPal Details</h4>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="paypal" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">Account</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8">';
				$content.='<input type="text" id="paypal" class="libr8-form-control textinput" value="'.$config['bankPayPal'].'" data-dbid="1" data-dbt="config" data-dbc="bankPayPal" placeholder="Enter a PayPal Account...">';
				$content.='<div id="paypalsave" class="libr8-input-group-btn libr8-hidden">';
					$content.='<button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button>';
				$content.='</div>';
			$content.='</div>';
		$content.='</div>';
		$content.='<div class="libr8-form-group">';
			$content.='<label for="ipn" class="libr8-control-label libr8-col-lg-1 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">IPN</label>';
			$content.='<div class="libr8-input-group libr8-col-lg-11 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8"><input type="text" id="ipn" class="libr8-form-control" value="" readonly></div></div><h4>Order Processing</h4><div class="libr8-form-group"><label for="pay_ti" class="libr8-control-label libr8-col-lg-2 libr8-col-md-3 libr8-col-sm-3 libr8-col-xs-5">Allow</label><div class="input-group libr8-col-lg-10 libr8-col-md-9 libr8-col-sm-9 libr8-col-xs-7"><select id="pay_ti" class="libr8-form-control" onchange="update(\'1\',\'config\',\'orderPayti\',$(this).val());"><option value="0"';
    if($config['orderPayti']==0){$content.=' selected';}
    $content.='>0 Days</option><option value="604800"';
    if($config['orderPayti']==604800){$content.=' selected';}
    $content.='>7 Days</option><option value="1209600"';
    if($config['orderPayti']==1209600){$content.=' selected';}
    $content.='>14 Days</option><option value="1814400"';
    if($config['orderPayti']==1814400){$content.=' selected';}
    $content.='>21 Days</option><option value="2592000"';
    if($config['orderPayti']==2592000){$content.=' selected';}
    $content.='>30 Days</option></select><div class="libr8-input-group-addon">for Payments</div></div></div><div class="libr8-form-group"><label for="email_subject" class="libr8-control-label libr8-col-lg-2 libr8-col-md-3 libr8-col-sm-3 libr8-col-xs-5">Email Subject</label><div class="libr8-input-group libr8-col-lg-10 libr8-col-md-9 libr8-col-sm-9 libr8-col-xs-7"><input type="text" id="email_subject" class="libr8-form-control libr8-textinput" value="'.$config['orderEmailDefaultSubject'].'" data-dbid="1" data-dbt="config" data-dbc="orderEmailDefaultSubject"><div id="email_subjectsave" class="libr8-input-group-btn libr8-hidden"><button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button></div><span class="libr8-help-block">You can use the following Tokens: {name} {first} {last} {date} {order_number}</span></div></div><div class="libr8-form-group"><label for="order_email_layout" class="libr8-control-label libr8-col-lg-2 libr8-col-md-3 libr8-col-sm-3 libr8-col-xs-5">Email Layout</label><div class="libr8-input-group libr8-col-lg-10 libr8-col-md-9 libr8-col-sm-9 libr8-col-xs-7"><form method="post" target="sp" action="includes/update.php"><input type="hidden" name="id" value="1"><input type="hidden" name="t" value="config"><input type="hidden" name="c" value="orderEmailLayout"><textarea id="order_email_layout" class="libr8-form-control summernote" name="da">'.$config['orderEmailLayout'].'</textarea></form><span class="libr8-help-block">You can use the following Tokens: {name} {first} {last} {date} {order_number} {notes}</span></div></div><div class="libr8-form-group"><label for="order_notes" class="libr8-control-label libr8-col-lg-2 libr8-col-md-3 libr8-col-sm-3 libr8-col-xs-5">Order Notes</label><div class="libr8-input-group libr8-col-lg-10 libr8-col-md-9 libr8-col-sm-9 libr8-col-xs-7"><form method="post" target="sp" action="includes/update.php"><input type="hidden" name="id" value="1"><input type="hidden" name="t" value="config"><input type="hidden" name="c" value="orderEmailNotes"><textarea id="order_notes" class="libr8-form-control summernote" name="da">'.$config['orderEmailNotes'].'</textarea></form><span class="libr8-help-block">You can use the following Tokens: {name} {first} {last} {date} {order_number} {notes}</span></div></div></div><div id="seo" class="libr8-tab-pane libr8-fade"><h4>Analytics</h4><div class="libr8-form-group"><label for="configseoTitle" class="libr8-control-label libr8-col-lg-2 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">seoTitle</label><div class="libr8-input-group libr8-col-lg-10 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8"><input type="text" id="configseoTitle" class="libr8-form-control libr8-textinput" value="'.$config['seoTitle'].'" data-dbid="1" data-dbt="config" data-dbc="seoTitle" placeholder="Enter a Page Title..."><div id="configseoTitlesave" class="libr8-input-group-btn libr8-hidden"><button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button></div></div></div><div class="libr8-form-group"><label for="configseoCaption" class="libr8-control-label libr8-col-lg-2 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">seoCaption</label><div class="libr8-input-group libr8-col-lg-10 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8"><input type="text" id="configseoCaption" class="libr8-form-control libr8-textinput" value="'.$config['seoCaption'].'" data-dbid="1" data-dbt="config" data-dbc="seoCaption" placeholder="Enter a Page Caption..."><div id="configseoCaptionsave" class="libr8-input-group-btn libr8-hidden"><button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button></div></div></div><div class="libr8-form-group"><label for="configseoDescription" class="libr8-control-label libr8-col-lg-2 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">seoDescription</label><div class="libr8-input-group libr8-col-lg-10 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8"><input type="text" id="configseoDescription" class="libr8-form-control libr8-textinput" value="'.$config['seoDescription'].'" data-dbid="1" data-dbt="config" data-dbc="seoDescription" placeholder="Enter a Page Description..."><div id="configseoDescriptionsave" class="libr8-input-group-btn libr8-hidden"><button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button></div></div></div><div class="libr8-form-group"><label for="configseoKeywords" class="libr8-control-label libr8-col-lg-2 libr8-col-md-2 libr8-col-sm-2 libr8-col-xs-4">seoKeywords</label><div class="libr8-input-group libr8-col-lg-10 libr8-col-md-10 libr8-col-sm-10 libr8-col-xs-8"><input type="text" id="configseoKeywords" class="libr8-form-control textinput" value="'.$config['seoKeywords'].'" data-dbid="1" data-dbt="config" data-dbc="seoKeywords" placeholder="Enter Page Keywords..."><div id="configseoKeywordssave" class="libr8-input-group-btn libr8-hidden"><button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button></div></div></div><div class="libr8-well"><h4>Google</h4><div class="libr8-form-group"><label for="sti" class="libr8-control-label libr8-col-lg-2 libr8-col-md-3 libr8-col-sm-3 libr8-col-xs-5">Acquire Date</label><div class="libr8-input-group libr8-col-lg-10 libr8-col-md-9 libr8-col-sm-9 libr8-col-xs-7"><select id="sti" class="libr8-form-control" onchange="update(\'1\',\'config\',\'sti\',$(this).val())"><option value="0">Every Time</option><option value="3600"';
    if($config['sti']==3600){$content.=' selected';}
    $content.='>Hourly</option><option value="86400"';
    if($config['sti']==86400){$content.=' selected';}
    $content.='>Daily</option><option value="2592000"';
    if($config['sti']==2592000){$content.=' selected';}
    $content.='>Monthly</option></select></div></div><div class="libr8-form-group"><label for="google_verification" class="libr8-control-label libr8-col-lg-2 libr8-col-md-3 libr8-col-sm-3 libr8-col-xs-5">Verification</label><div class="libr8-input-group libr8-col-lg-10 libr8-col-md-9 libr8-col-sm-9 libr8-col-xs-7"><input type="text" id="google_verification" class="libr8-form-control textinput" value="'.$config['seoGoogleVerification'].'" data-dbid="1" data-dbt="config" data-dbc="seoGoogleVerification" placeholder="Enter Google Site Verification Code..."><div id="google_verificationsave" class="libr8-input-group-btn libr8-hidden"><button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button></div></div></div><div class="libr8-form-group"><label for="options6" class="libr8-control-label libr8-col-lg-2 libr8-col-md-3 libr8-col-sm-3 libr8-col-xs-5 libr8-text-right"><input type="checkbox" id="options6" data-dbid="1" data-dbt="config" data-dbc="options" data-dbb="6"';
    if($config['options']{6}==1){$content.=' checked';}
    $content.='></label><div class="libr8-input-group libr8-col-lg-10 libr8-col-md-9 libr8-col-sm-9 libr8-col-xs-7">Enable Analytics</div></div><div class="libr8-form-group"><label for="google_tracking" class="libr8-control-label libr8-col-lg-2 libr8-col-md-3 libr8-col-sm-3 libr8-col-xs-5"><small>Domain</small></label><div class="libr8-input-group libr8-col-lg-10 libr8-col-md-9 libr8-col-sm-9 libr8-col-xs-7"><input type="text" id="google_domain" class="libr8-form-control libr8-textinput" value="'.$config['seoGoogleDomain'].'" data-dbid="1" data-dbt="config" data-dbc="seoGoogleDomain" placeholder="Enter the Domain as Provided by Google..."><div id="google_domainsave" class="libr8-input-group-btn libr8-hidden"><button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button></div></div></div></div><div class="libr8-well"><h4>Bing</h4><div class="libr8-form-group"><label for="bing_verification" class="libr8-control-label libr8-col-lg-2 libr8-col-md-3 libr8-col-sm-3 libr8-col-xs-5">Verification</label><div class="libr8-input-group libr8-col-lg-10 libr8-col-md-9 libr8-col-sm-9 libr8-col-xs-7"><input type="text" id="bing_verification" class="libr8-form-control textinput" value="'.$config['seoBingVerification'].'" data-dbid="1" data-dbt="config" data-dbc="seoBingVerification" placeholder="Enter Bing Site Verification Code..."><div id="bing_verificationsave" class="libr8-input-group-btn libr8-hidden"><button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button></div></div></div></div><div class="libr8-well"><h4>Pinterest</h4><div class="libr8-form-group"><label for="pinterest_verification" class="libr8-control-label libr8-col-lg-2 libr8-col-md-3 libr8-col-sm-3 libr8-col-xs-5">Verification</label><div class="libr8-input-group libr8-col-lg-10 libr8-col-md-9 libr8-col-sm-9 libr8-col-xs-7"><input type="text" id="pinterest_verification" class="libr8-form-control libr8-textinput" value="'.$config['seoPinterestVerification'].'" data-dbid="1" data-dbt="config" data-dbc="seoPinterestVerification" placeholder="Enter Pinterest Verification Code..."><div id="pinterest_verificationsave" class="libr8-input-group-btn libr8-hidden"><button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button></div></div></div></div></div><div id="security" class="libr8-tab-pane libr8-fade"><div class="libr8-form-group"><label class="libr8-control-label libr8-col-lg-2 libr8-col-md-3 libr8-col-sm-3 libr8-col-xs-5">&nbsp;</label><div class="libr8-input-group libr8-col-lg-10 libr8-col-md-9 libr8-col-sm-9 libr8-col-xs-7"><div class="libr8-alert libr8-alert-info">To use project honey pot\'s spam traps you must sign up, and setup a trap with <a target="_blank" href="http://www.projecthoneypot.org/?rf=80644">Project Honey Pot</a></div></div></div><div class="libr8-form-group"><label for="project_honey_pot" class="libr8-control-label libr8-col-lg-2 libr8-col-md-3 libr8-col-sm-3 libr8-col-xs-5">PHP Page Links</label><div class="libr8-input-group libr8-col-lg-10 libr8-col-md-9 libr8-col-sm-9 libr8-col-xs-7"><select id="project_honey_pot" class="libr8-form-control" onchange="update(\'1\',\'config\',\'PHP\',$(this).val());"><option value=""';
    if($config['PHP']==''){$content.=' selected';}
    $content.='>Do Not Use</option><option value="quick"';
    if($config['PHP']=='quick'){$content.=' selected';}
    $content.='>Use Quick Link</option><option value="random"';
    if($config['PHP']=='random'){$content.=' selected';}
    $content.='>Use Random Link</option></select></div></div><div class="libr8-form-group"><label for="honey_pot_file" class="libr8-control-label libr8-col-lg-2 libr8-col-md-3 libr8-col-sm-3 libr8-col-xs-5">Honey Pot File</label><div class="libr8-input-group libr8-col-lg-10 libr8-col-md-9 libr8-col-sm-9 libr8-col-xs-7"><input type="text" id="honey_pot_file" class="libr8-form-control libr8-textinput" value="'.$config['PHPFile'].'" data-dbid="1" data-dbt="config" data-dbc="PHPFile" placeholder="This is the file uploaded to the server including folders..."><div id="honey_pot_filesave" class="libr8-input-group-btn libr8-hidden"><button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button></div></div></div><div class="libr8-form-group"><label for="honey_pot_quick" class="libr8-control-label libr8-col-lg-2 libr8-col-md-3 libr8-col-sm-3 libr8-col-xs-5">Honey Pot Quick Link</label><div class="libr8-input-group libr8-col-lg-10 libr8-col-md-9 libr8-col-sm-9 libr8-col-xs-7"><input type="text" id="honey_pot_quick" class="libr8-form-control libr8-textinput" value="'.$config['PHPQuickLink'].'" data-dbid="1" data-dbt="config" data-dbc="PHPQuickLink" placeholder="This is the Quick Link URL as provided..."><div id="honey_pot_quicksave" class="libr8-input-group-btn libr8-hidden"><button class="libr8-btn libr8-btn-danger"><i class="fa fa-save"></i></button></div></div></div><div id="backup" class="libr8-well" name="backup"><h4>Database Backup/Restore</h4><div class="libr8-form-group"><label class="libr8-control-label libr8-col-lg-2 libr8-col-md-3 libr8-col-sm-3 libr8-col-xs-5">Backup</label><form target="sp" method="post" action="includes/backup.php"><div class="libr8-input-group libr8-col-lg-10 libr8-col-md-9 libr8-col-sm-9 libr8-col-xs-7"><div class="libr8-input-group-btn"><button type="submit" class="libr8-btn libr8-btn-default libr8-btn-block" onclick="$(\'#block\').css({\'display\':\'block\'});">Go</button></div></div></form></div><div class="libr8-form-group"><label class="libr8-control-label libr8-col-lg-2 libr8-col-md-3 libr8-col-sm-3 libr8-col-xs-5">Restore</label><form target="sp" method="post" enctype="multipart/form-data" action="includes/restore.php"><div class="libr8-input-group libr8-col-lg-10 libr8-col-md-9 libr8-col-sm-9 libr8-col-xs-7"><input type="file" id="fu" class="libr8-form-control" name="fu" data-icon="false" accept="application/x-gzip,application/sql"><div class="libr8-input-group-btn"><button type="submit" class="libr8-btn libr8-btn-default" onclick="$(\'#block\').css({\'display\':\'block\'});">Restore</button></div></div></form></div>';
	foreach(glob("media/backup/backup_*") as $file){
		$file=ltrim($file,'media/backup/');
        $content.='<div id="l_'.str_replace('.','',$file).'" class="libr8-form-group"><label class="libr8-control-label libr8-col-lg-2 libr8-col-md-3 libr8-col-sm-3 libr8-col-xs-5">&nbsp;</label><div class="libr8-input-group libr8-col-lg-10 libr8-col-md-9 libr8-col-sm-9 libr8-col-xs-7"><a class="libr8-btn libr8-btn-default libr8-btn-block" href="media/'.$file.'">'.$file.'</a><div class="libr8-input-group-btn"><button class="libr8-btn libr8-btn-danger" onclick="removeMedia(\''.$file.'\')">Delete</button></div></div></div>';
	}
    $content.='</div></div></div>';
}else{
	include'includes/noaccess.php';
}
	$content.='</div></div></main>';
